import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import AgeDropDown from "../../components/form/AgeDropDown";

const Age: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FluffyCare | Step 4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center flex-col max-h-full">
        <div className="h-48 flex items-end justify-center p-4 w-full lg:w-3/4">
          <h1 className="text-3xl md:text-4xl font-bold text-center">
            Cool! How old is Sprinkles?
          </h1>
        </div>
        <div className="h-72 flex justify-center items-center w-full md:w-1/2 lg:w-1/3">
          <div className="w-full">
            <AgeDropDown />
          </div>
        </div>

        <div className="h-32 flex justify-center items-end md:items-center py-6 w-full">
          <Link href="/get-a-quote/boy-or-girl">
            <button
              type="button"
              onClick={() => {}}
              className="inline-flex items-center justify-center w-full md:w-1/3 lg:w-1/4 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              Continue
            </button>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Age;
