import { RadioGroup } from "@headlessui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { Button } from "../../components/shared/Button";
import { useQuote } from "../../store/quote";
import { OnboardingWrapper } from "../../components/shared/OnboardingWrapper";

const plans = [
  {
    id: "male",
    name: "Boy",
  },
  {
    id: "female",
    name: "Girl",
  },
];

const BoyOrGirl: NextPage = () => {
  const router = useRouter();
  const [quote, setQuote] = useQuote();

  let [plan, setPlan] = useState(quote.pet_sex);

  const handleContinue = () => {
    router.push("/get-a-quote/breed");
    setQuote({
      ...quote,
      pet_sex: plan,
    });
  };

  return (
    <OnboardingWrapper>
      <Head>
        <title>FluffyCare | Step 5</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center flex-col max-h-full">
        <div className="h-48 flex items-end justify-center p-4 w-full lg:w-3/4">
          <h1 className="text-3xl md:text-4xl font-bold text-center">
            Perfect! Is {quote.pet_name} a boy or a girl?{" "}
          </h1>
        </div>
        <div className="h-72 flex justify-center items-baseline md:items-center w-full md:w-1/2 lg:w-1/3">
          <RadioGroup value={plan} onChange={setPlan}>
            <RadioGroup.Option value="female">
              {({ checked }) => (
                <div
                  key={plans[1].id}
                  className="relative flex items-center mb-12"
                >
                  <div className="flex items-center h-5">
                    <input
                      id={plans[1].id}
                      aria-describedby={`${plans[1].id}-description`}
                      name="plan"
                      type="radio"
                      defaultChecked={checked}
                      className="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300"
                    />
                  </div>
                  <div className="ml-3 text-2xl">
                    <label
                      htmlFor={plans[1].id}
                      className="font-medium text-gray-700"
                    >
                      {plans[1].name}
                    </label>
                  </div>
                </div>
              )}
            </RadioGroup.Option>
            <RadioGroup.Option value="male">
              {({ checked }) => (
                <div
                  key={plans[0].id}
                  className="relative flex items-center mb-12"
                >
                  <div className="flex items-center h-5">
                    <input
                      id={plans[0].id}
                      aria-describedby={`${plans[0].id}-description`}
                      name="plan"
                      type="radio"
                      defaultChecked={checked}
                      className="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300"
                    />
                  </div>
                  <div className="ml-3 text-2xl">
                    <label
                      htmlFor={plans[0].id}
                      className="font-medium text-gray-700"
                    >
                      {plans[0].name}
                    </label>
                  </div>
                </div>
              )}
            </RadioGroup.Option>
          </RadioGroup>
        </div>

        <div className="h-32 flex justify-center items-end md:items-center py-6 w-full">
          <Button
            onClick={handleContinue}
            text="Continue"
            disabled={plan.length == 0}
          />
        </div>
      </main>
    </OnboardingWrapper>
  );
};

export default BoyOrGirl;
