import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import BreedSearchBox from "../../components/form/BreedSearchBox";
import { Button } from "../../components/shared/Button";
import { useQuote } from "../../store/quote";
import { OnboardingWrapper } from "../../components/shared/OnboardingWrapper";

const Breed: NextPage = () => {
  const router = useRouter();
  const [quote, setQuote] = useQuote();

  const [selected, setSelected] = useState<string>(quote.breed);

  const handleContinue = () => {
    setQuote({
      ...quote,
      breed: selected,
    });
    router.push("/get-a-quote/extra-pets");
  };
  return (
    <OnboardingWrapper>
      <Head>
        <title>FluffyCare | Step 6</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center flex-col max-h-full">
        <div className="h-48 flex items-end justify-center p-4 w-full lg:w-3/4">
          <h1 className="text-3xl md:text-4xl font-bold text-center">
            Aww! I bet {quote.pet_sex === "male" ? "he's" : "she's"} a good{" "}
            {quote.pet_sex === "male" ? "boy" : "girl"}! What kind of{" "}
            {quote.dog_or_cat} is {quote.pet_sex === "male" ? "he" : "she"}?
          </h1>
        </div>
        <div className="h-72 flex justify-center items-baseline md:items-center w-full md:w-1/2 lg:w-1/3">
          {/* @ts-ignore */}
          <BreedSearchBox
            dog_or_cat={quote.dog_or_cat}
            selected={selected}
            setSelected={({ name }: { name: string }) => {
              setSelected(name);
            }}
          />
        </div>

        <div className="h-32 flex justify-center items-end md:items-center py-6 w-full">
          <Button
            onClick={handleContinue}
            text="Continue"
            disabled={!selected}
          />
        </div>
      </main>
    </OnboardingWrapper>
  );
};

export default Breed;
