import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import InputBox from "../../components/form/InputBox";

const plans = [
  {
    id: "yes",
    name: "Yes",
  },
  {
    id: "No",
    name: "No",
  },
];

const ExtraPets: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FluffyCare | Step 7</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center flex-col max-h-full">
        <div className="h-48 flex items-end justify-center p-4 w-full lg:w-3/4">
          <h1 className="text-3xl md:text-4xl font-bold text-center">
            Out of curiosity, is there any more cats or dogs living with ya’ll?
          </h1>
        </div>
        <div className="h-72 flex justify-center items-baseline md:items-center w-full md:w-1/2 lg:w-1/3">
          <fieldset>
            <legend className="sr-only">Sex</legend>
            <div className="space-y-5">
              {plans.map((plan) => (
                <div key={plan.id} className="relative flex items-center mb-12">
                  <div className="flex items-center h-5">
                    <input
                      id={plan.id}
                      aria-describedby={`${plan.id}-description`}
                      name="plan"
                      type="radio"
                      className="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300"
                    />
                  </div>
                  <div className="ml-3 text-2xl">
                    <label
                      htmlFor={plan.id}
                      className="font-medium text-gray-700"
                    >
                      {plan.name}
                    </label>
                  </div>
                </div>
              ))}
            </div>
          </fieldset>{" "}
        </div>

        <div className="h-32 flex justify-center items-end md:items-center py-6 w-full">
          <Link href="/get-a-quote/signup">
            <button
              type="button"
              onClick={() => {}}
              className="inline-flex items-center justify-center w-full md:w-1/3 lg:w-1/4 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              Continue
            </button>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default ExtraPets;
