import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "../../components/shared/Button";
import { RadioGroup } from "@headlessui/react";
import { useState } from "react";
import { useRouter } from "next/router";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../../config/firebase";
import { OnboardingWrapper } from "../../components/shared/OnboardingWrapper";

const plans = [
  {
    id: "yes",
    name: "Yes",
  },
  {
    id: "No",
    name: "No",
  },
];

const ExtraPets: NextPage = () => {
  const router = useRouter();
  const [user] = useAuthState(auth);

  let [plan, setPlan] = useState("");

  const handleContinue = () => {
    if (user) {
      router.push("/get-a-quote/calculating");
    } else {
      router.push("/get-a-quote/signup");
    }
  };

  return (
    <OnboardingWrapper>
      <Head>
        <title>FluffyCare | Step 7</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center flex-col max-h-full">
        <div className="h-48 flex items-end justify-center p-4 w-full lg:w-3/4">
          <h1 className="text-3xl md:text-4xl font-bold text-center">
            Out of curiosity, is there any more cats or dogs living with ya’ll?
          </h1>
        </div>
        <div className="h-92 flex justify-center items-center md:items-center w-full md:w-1/2 lg:w-1/3 flex-col my-12">
          <RadioGroup value={plan} onChange={setPlan}>
            <RadioGroup.Option value="no">
              {({ checked }) => (
                <div
                  key={plans[1].id}
                  className="relative flex items-center mb-12"
                >
                  <div className="flex items-center h-5">
                    <input
                      id={plans[1].id}
                      aria-describedby={`${plans[1].id}-description`}
                      name="plan"
                      type="radio"
                      defaultChecked={checked}
                      className="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300"
                    />
                  </div>
                  <div className="ml-3 text-2xl">
                    <label
                      htmlFor={plans[1].id}
                      className="font-medium text-gray-700"
                    >
                      {plans[1].name}
                    </label>
                  </div>
                </div>
              )}
            </RadioGroup.Option>
            <RadioGroup.Option value="yes">
              {({ checked }) => (
                <div
                  key={plans[0].id}
                  className="relative flex items-center mb-4"
                >
                  <div className="flex items-center h-5">
                    <input
                      id={plans[0].id}
                      aria-describedby={`${plans[0].id}-description`}
                      name="plan"
                      type="radio"
                      defaultChecked={checked}
                      className="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300"
                    />
                  </div>
                  <div className="ml-3 text-2xl">
                    <label
                      htmlFor={plans[0].id}
                      className="font-medium text-gray-700"
                    >
                      {plans[0].name}
                    </label>
                  </div>
                </div>
              )}
            </RadioGroup.Option>
          </RadioGroup>

          {plan === "yes" && (
            <div className="rounded-md bg-gray-50 p-4">
              <div className="flex">
                <div className="flex-shrink-0"></div>
                <div className="ml-3">
                  <h3 className="text-sm leading-5 font-medium text-gray-800">
                    Great!
                  </h3>
                  <div className="mt-2 text-sm leading-5 text-gray-700">
                    <ul className="list-disc pl-5">
                      <li>
                        We can work on adding your other animals to your plan
                        after we finish. Also you will receive a discount for
                        any extra pet your add!
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        <div className="h-32 flex justify-center items-end md:items-center py-6 w-full">
          <Button
            onClick={handleContinue}
            text="Continue"
            disabled={plan.length == 0}
          />
        </div>
      </main>
    </OnboardingWrapper>
  );
};

export default ExtraPets;
