import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { CheckIcon } from "@heroicons/react/outline";
import { useBreakpoint } from "../../hooks/useBreakpoint";
import PaymentModal from "../../components/modals/PaymentModal";
import { useQuote } from "../../store/quote";

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(" ");
}

const Plans: NextPage = () => {
  const router = useRouter();
  const [quote, setQuote] = useQuote();

  const { isSm } = useBreakpoint("sm");
  const [open, setOpen] = useState(false);

  let pricing = {
    tiers: [
      {
        title: "Bronze Plan",
        price: 24,
        frequency: "/month",
        description:
          "The essentials to provide the basic health coverage for Sprinkles.",
        features: [
          "5 vet visits",
          "Up to $1,000 spending limit",
          "15 vaccines ",
          "48-hour claim response time",
        ],
        cta: "Purchase",
        mostPopular: false,
      },
      {
        title: "Silver Plan",
        price: 32,
        frequency: "/month",
        description:
          "The essentials to provide the basic health coverage for Sprinkles.",
        features: [
          "25 vet visits",
          "5 vet visits",
          "Up to $1,000 spending limit",
          "15 vaccines ",
          "48-hour claim response time",
        ],
        cta: "Purchase",
        mostPopular: true,
      },
      {
        title: "Gold Plan",
        price: 48,
        frequency: "/month",
        description:
          "The essentials to provide the basic health coverage for Sprinkles.",
        features: [
          "5 vet visits",
          "Up to $1,000 spending limit",
          "5 vet visits",
          "Up to $1,000 spending limit",
          "15 vaccines ",
          "48-hour claim response time",
        ],
        cta: "Purchase",
        mostPopular: false,
      },
    ],
  };

  return (
    <div>
      <Head>
        <title>FluffyCare | Step 8</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-7xl mx-auto py-24 px-4 bg-white sm:px-6 lg:px-8">
        <h1 className="text-3xl md:text-4xl font-bold text-center">
          Hooray! Here are the best plans that we found for {quote.pet_name}
        </h1>

        {/* Tiers */}
        <div className="mt-24 space-y-12 lg:space-y-0 lg:grid lg:grid-cols-3 lg:gap-x-8">
          {pricing.tiers.map((tier) => (
            <div
              key={tier.title}
              className="relative p-8 bg-white border border-gray-200 rounded-2xl shadow-sm flex flex-col"
            >
              <div className="flex-1">
                <h3 className="text-xl font-semibold text-gray-900">
                  {tier.title}
                </h3>
                {tier.mostPopular ? (
                  <p className="absolute top-0 py-1.5 px-4 bg-blue-500 rounded-full text-xs font-semibold uppercase tracking-wide text-white transform -translate-y-1/2">
                    Most popular
                  </p>
                ) : null}
                <p className="mt-4 flex items-baseline text-gray-900">
                  <span className="text-5xl font-extrabold tracking-tight">
                    ${tier.price}
                  </span>
                  <span className="ml-1 text-xl font-semibold">
                    {tier.frequency}
                  </span>
                </p>
                <p className="mt-6 text-gray-500">{tier.description}</p>

                {/* Feature list */}
                <ul role="list" className="mt-6 space-y-6">
                  {tier.features.map((feature) => (
                    <li key={feature} className="flex">
                      <CheckIcon
                        className="flex-shrink-0 w-6 h-6 text-blue-500"
                        aria-hidden="true"
                      />
                      <span className="ml-3 text-gray-500">{feature}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <button
                className={classNames(
                  tier.mostPopular
                    ? "bg-blue-500 text-white hover:bg-blue-600"
                    : "bg-blue-50 text-blue-700 hover:bg-blue-100",
                  "mt-8 block w-full py-3 px-6 border border-transparent rounded-md text-center font-medium"
                )}
                onClick={() => setOpen(true)}
              >
                {tier.cta}
              </button>
            </div>
          ))}
        </div>
        <PaymentModal open={open} setOpen={setOpen} />
      </main>
    </div>
  );
};

export default Plans;
